PREFIX obo:   <http://purl.obolibrary.org/obo/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pmdco: <https://w3id.org/pmd/co/>

SELECT ?subprocess ?subprocessLabel (COUNT(?prev) AS ?orderIndex)
WHERE {
  # pick one parent tensile testing process
  {
    SELECT ?mainProcess WHERE {
      ?mainProcess a pmdco:PMD_0000974 .
    }
    LIMIT 1
  }

  # child subprocesses
  ?subprocess obo:BFO_0000132 ?mainProcess .
  OPTIONAL { ?subprocess (obo:BFO_0000062)+ ?prev }

  OPTIONAL { ?subprocess rdfs:label ?subprocessLabel }
}
GROUP BY ?subprocess ?subprocessLabel
ORDER BY ?orderIndex